import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,symlinkSync,realpathSync} from 'node:fs';
import {homedir,tmpdir} from 'node:os';
import {join} from 'node:path';
import {loadProfileResources} from '../../extensions/startup-profile/profile-resources.ts';
function fixture(){const directory=mkdtempSync(join(tmpdir(),'profile-resources-'));return {id:'research',label:'Research',description:'',instructions:'',directory};}
function put(root:string,path:string,text:string){const file=join(root,path);mkdirSync(join(file,'..'),{recursive:true});writeFileSync(file,text);return file;}
const skill='---\nname: check\ndescription: check evidence\n---\nLOCAL';
const agent='---\nname: investigator\ndescription: investigate\nskills: check\ntools: []\n---\nInvestigate evidence.';
test('common_skill_wins_for_parent_and_child',()=>{const p=fixture();put(p.directory,'skills/check/SKILL.md',skill);put(p.directory,'agents/investigator.md',agent);const common=put(mkdtempSync(join(tmpdir(),'common-')),'check/SKILL.md',skill.replace('LOCAL','COMMON'));const r=loadProfileResources(p,[{name:'check',filePath:common}]);assert.deepEqual(r.skillPaths,[]);assert.deepEqual(r.agents[0].definition.skillPath,[common]);assert.equal(r.agents[0].name,'profile.research.investigator');assert.ok(r.warnings.length);});
test('preserves_empty_tools',()=>{const p=fixture();put(p.directory,'skills/check/SKILL.md',skill);put(p.directory,'agents/investigator.md',agent);const r=loadProfileResources(p,[]);assert.deepEqual(r.agents[0].definition.tools,[]);assert.equal(r.agents[0].definition.inheritGlobalContext,true);assert.equal(r.agents[0].definition.systemPromptMode,'append');});
test('rejects_unknown_agent_fields',()=>{const p=fixture();put(p.directory,'agents/a.md',agent.replace('skills: check','unsupported: yes'));const r=loadProfileResources(p,[]);assert.equal(r.agents.length,0);assert.ok(r.warnings.length);});
test('rejects_duplicate_agent_names',()=>{const p=fixture();put(p.directory,'skills/check/SKILL.md',skill);for(const f of ['a','b'])put(p.directory,'agents/'+f+'.md',agent);assert.equal(loadProfileResources(p,[]).agents.length,0);});
test('rejects_nested_skill_symlink_escape',()=>{const p=fixture();const other=fixture();put(other.directory,'check/SKILL.md',skill);mkdirSync(join(p.directory,'skills'));symlinkSync(join(other.directory,'check'),join(p.directory,'skills/check'));const r=loadProfileResources(p,[]);assert.equal(r.skillPaths.length,0);assert.ok(r.warnings.length);});
test('missing_optional_directories_are_empty',()=>{const p=fixture();assert.deepEqual(loadProfileResources(p,[]),{skillPaths:[],agents:[],warnings:[]});});
test('missing_selected_skill_is_diagnosed',()=>{const p=fixture();put(p.directory,'agents/a.md',agent);const r=loadProfileResources(p,[]);assert.equal(r.agents.length,0);assert.ok(r.warnings.length);});
test('rejects_child_skill_folder_name_mismatch',()=>{const p=fixture();put(p.directory,'skills/different/SKILL.md',skill);put(p.directory,'agents/a.md',agent);const r=loadProfileResources(p,[]);assert.equal(r.skillPaths.length,1);assert.equal(r.agents.length,0);assert.ok(r.warnings.some(w=>w.includes('skill name')));});
for(const tool of ['/tmp/extension.js','../extension.ts','extension.js','extension.ts','mcp:server/tool'])test('rejects_extension_path_tool '+tool,()=>{const p=fixture();put(p.directory,'agents/a.md',agent.replace('skills: check\n','').replace('tools: []','tools: '+JSON.stringify([tool])));const r=loadProfileResources(p,[]);assert.equal(r.agents.length,0);assert.ok(r.warnings.length);});
test('skill_directory_does_not_trigger_unvalidated_sdk_recursion',()=>{const p=fixture();const outside=fixture();put(outside.directory,'escaped/SKILL.md',skill);mkdirSync(join(p.directory,'skills/check/SKILL.md'),{recursive:true});symlinkSync(join(outside.directory,'escaped'),join(p.directory,'skills/check/escaped'));const r=loadProfileResources(p,[]);assert.deepEqual(r.skillPaths,[]);assert.ok(r.warnings.length);});
test('ignored_skill_file_does_not_trigger_unvalidated_sdk_recursion',()=>{const p=fixture();const outside=fixture();put(outside.directory,'escaped/SKILL.md',skill.replace('check','escaped'));put(p.directory,'skills/check/SKILL.md',skill);put(p.directory,'skills/check/.gitignore','SKILL.md\n');symlinkSync(join(outside.directory,'escaped'),join(p.directory,'skills/check/escaped'));const r=loadProfileResources(p,[]);assert.ok(r.skillPaths.every(path=>path.startsWith(realpathSync(p.directory)+'/')));assert.equal(r.skillPaths.length,1);});
const coder='---\nname: coder\ndescription: write code\n---\nWrite code.';
const manager=(extra:string)=>'---\nname: manager\ndescription: manage\ntools: read, subagent\n'+extra+'\n---\nManage work.';
test('accepts_pi_subagents_fields',()=>{const p=fixture();put(p.directory,'agents/coder.md',coder);put(p.directory,'agents/manager.md',manager('advertise: false\nextensions:\n  - ~/ext/lens.js\n  - /opt/ext/other.js\ndefaultContext: fresh\nasync: true\nacceptanceRole: writer\nallowNestedSubagents: true\nallowedAgents:\n  - coder\n  - scout'));const r=loadProfileResources(p,[]);assert.deepEqual(r.warnings,[]);const m=r.agents.find(a=>a.name==='profile.research.manager')!;assert.equal(m.advertise,false);assert.deepEqual(m.definition.extensions,[join(homedir(),'ext/lens.js'),'/opt/ext/other.js']);assert.equal(m.definition.defaultContext,'fresh');assert.equal(m.definition.defaultAsync,true);assert.equal(m.definition.acceptanceRole,'writer');assert.equal(m.definition.allowNestedSubagents,true);assert.deepEqual(m.definition.allowedAgents,['profile.research.coder','scout']);assert.equal(r.agents.find(a=>a.name==='profile.research.coder')!.advertise,undefined);});
test('keeps_empty_allowed_agents_as_deny_all',()=>{const p=fixture();put(p.directory,'agents/manager.md',manager('allowNestedSubagents: true\nallowedAgents: []'));const r=loadProfileResources(p,[]);assert.deepEqual(r.agents[0].definition.allowedAgents,[]);});
test('maps_allowed_sibling_even_when_sibling_is_invalid',()=>{const p=fixture();put(p.directory,'agents/coder.md',coder.replace('---\nWrite','unsupported: yes\n---\nWrite'));put(p.directory,'agents/manager.md',manager('allowedAgents: coder'));const r=loadProfileResources(p,[]);assert.deepEqual(r.agents.map(a=>a.name),['profile.research.manager']);assert.deepEqual(r.agents[0].definition.allowedAgents,['profile.research.coder']);});
for(const [field,value] of [['extensions','relative/ext.js'],['extensions','~user/ext.js'],['defaultContext','reuse'],['async','yes'],['acceptanceRole','admin'],['allowNestedSubagents','sometimes'],['advertise','maybe']])test('rejects_invalid_'+field+' '+value,()=>{const p=fixture();put(p.directory,'agents/manager.md',manager(field+': '+value));const r=loadProfileResources(p,[]);assert.equal(r.agents.length,0);assert.ok(r.warnings.some(w=>w.includes(field)),r.warnings.join('\n'));});
