import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, existsSync, chmodSync, readFileSync, statSync, readdirSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import extension from '../../extensions/startup-profile/index.ts';
function environment(t:any, override?:string) {
 const home=mkdtempSync(join(tmpdir(),'profile-home-'));
 const previous={HOME:process.env.HOME,PI_PROFILE_DIR:process.env.PI_PROFILE_DIR};
 process.env.HOME=home;
 if(override===undefined)delete process.env.PI_PROFILE_DIR;else process.env.PI_PROFILE_DIR=override;
 t.after(()=>{for(const [k,v] of Object.entries(previous))if(v===undefined)delete process.env[k];else process.env[k]=v;});
 return {home,root:join(home,'.pi/agent/profiles')};
}
function definition(root:string){mkdirSync(join(root,'personal/agents'),{recursive:true});writeFileSync(join(root,'catalog.json'),'[]');writeFileSync(join(root,'personal/profile.json'),JSON.stringify({id:'developer',label:'Personal',description:'home'}));writeFileSync(join(root,'personal/instructions.md'),'PERSONAL_RULE');writeFileSync(join(root,'personal/agents/helper.md'),'---\nname: helper\ndescription: home helper\n---\nHOME_AGENT');}
function harness(root?:string, saved=false){const handlers:Record<string,Function>={}, entries:any[]=saved?[{type:'custom',customType:'startup-profile-state',data:{version:1,id:'developer',label:'Old',instructions:'SAVED_RULE'}}]:[], notices:string[]=[], choices:string[]=[];const names=new Set<string>();const pi:any={on:(n:string,h:Function)=>handlers[n]=h,appendEntry:(customType:string,data:any)=>entries.push({type:'custom',customType,data}),getCommands:()=>[],events:{emit:(_n:string,r:any)=>{names.add(r.name);r.result={ok:true,registration:{dispose:()=>names.delete(r.name)}};}}};const ctx:any={mode:'tui',sessionManager:{getEntries:()=>entries,getSessionFile:()=>undefined,getSessionId:()=> 'home-test'},ui:{notify:(s:string)=>notices.push(s),setStatus(){},select:async(_t:string,opts:string[])=>{choices.push(...opts);return opts[0];}}};extension(pi,root);return {handlers,entries,notices,choices,names,ctx};}
test('default_home_only_not_samples',async t=>{const e=environment(t);definition(e.root);const h=harness();await h.handlers.session_start({reason:'startup'},h.ctx);assert.equal(h.entries[0].data.instructions,'PERSONAL_RULE');assert.equal(h.choices.length,2);assert.ok(h.choices[0].includes('Personal'));await h.handlers.resources_discover({},h.ctx);assert.deepEqual([...h.names],['profile.developer.helper']);});
test('missing_root_other_no_files_created',async t=>{const e=environment(t);const h=harness();await h.handlers.session_start({reason:'startup'},h.ctx);assert.equal(h.entries[0].data.id,'standard');assert.equal(h.choices.length,1);assert.ok(h.notices.length);assert.equal(existsSync(e.root),false);});
test('empty_root_no_bundled_profiles',async t=>{const e=environment(t);mkdirSync(e.root,{recursive:true});const h=harness();await h.handlers.session_start({reason:'startup'},h.ctx);assert.equal(h.entries[0].data.id,'standard');assert.equal(h.choices.length,1);});
test('file_root_other',async t=>{const e=environment(t);mkdirSync(join(e.home,'.pi/agent'),{recursive:true});writeFileSync(e.root,'file');const h=harness();await h.handlers.session_start({reason:'startup'},h.ctx);assert.equal(h.entries[0].data.id,'standard');assert.ok(h.notices.length);});
test('invalid_root_restores_snapshot_only',async t=>{const e=environment(t,'relative');definition(e.root);const h=harness(undefined,true);await h.handlers.session_start({reason:'resume'},h.ctx);assert.deepEqual((await h.handlers.resources_discover({},h.ctx)).skillPaths,[]);assert.equal(h.names.size,0);const event:any={systemPrompt:'BASE',systemPromptOptions:{sections:{}}};h.handlers.before_agent_start(event,h.ctx);assert.equal(event.systemPromptOptions.sections.startup_profile,'SAVED_RULE');assert.ok(h.notices.length);});
test('explicit_fixture_root_wins_over_env',async t=>{const e=environment(t,'invalid');const explicit=join(e.home,'fixture');definition(explicit);const h=harness(explicit);await h.handlers.session_start({reason:'startup'},h.ctx);assert.equal(h.entries[0].data.instructions,'PERSONAL_RULE');});
test('new_root_only_at_session_boundary_snapshot_preserved',async t=>{const e=environment(t);definition(e.root);const second=join(e.home,'second');definition(second);writeFileSync(join(second,'personal/agents/helper.md'),'---\nname: second\ndescription: second\n---\nSECOND_AGENT');const h=harness(undefined,true);await h.handlers.session_start({reason:'resume'},h.ctx);process.env.PI_PROFILE_DIR=second;await h.handlers.resources_discover({},h.ctx);assert.deepEqual([...h.names],['profile.developer.helper']);await h.handlers.session_start({reason:'reload'},h.ctx);await h.handlers.resources_discover({},h.ctx);assert.deepEqual([...h.names],['profile.developer.second']);const event:any={systemPrompt:'BASE',systemPromptOptions:{sections:{}}};h.handlers.before_agent_start(event,h.ctx);assert.equal(event.systemPromptOptions.sections.startup_profile,'SAVED_RULE');});
function unreadable(t:any,root:string){definition(root);writeFileSync(join(root,'catalog.json'),JSON.stringify([{id:'developer',label:'Legacy',description:'',instructionsFile:'legacy.md'}]));writeFileSync(join(root,'legacy.md'),'LEGACY_RULE');writeFileSync(join(root,'personal/profile.json'),JSON.stringify({id:'developer',label:'Disabled',description:'',enabled:false}));t.after(()=>chmodSync(root,0o700));chmodSync(root,0o111);assert.ok(statSync(root).isDirectory());assert.match(readFileSync(join(root,'catalog.json'),'utf8'),/Legacy/);assert.throws(()=>readdirSync(root),{code:'EACCES'});}
test('unreadable_root_must_not_revive_legacy',async t=>{if(process.getuid?.()===0)return t.skip('requires nonprivileged POSIX process');const e=environment(t);unreadable(t,e.root);const h=harness();await h.handlers.session_start({reason:'startup'},h.ctx);assert.equal(h.entries[0].data.id,'standard');assert.equal(h.choices.length,1);assert.ok(h.notices.length);});
test('unreadable_root_restores_saved_text_only',async t=>{if(process.getuid?.()===0)return t.skip('requires nonprivileged POSIX process');const e=environment(t);unreadable(t,e.root);const h=harness(undefined,true);await h.handlers.session_start({reason:'resume'},h.ctx);await h.handlers.resources_discover({},h.ctx);assert.equal(h.names.size,0);const event:any={systemPrompt:'BASE',systemPromptOptions:{sections:{}}};h.handlers.before_agent_start(event,h.ctx);assert.equal(event.systemPromptOptions.sections.startup_profile,'SAVED_RULE');assert.ok(h.notices.length);});
test('intentional_root_symlink_reads_personal_root',async t=>{const e=environment(t);const target=join(e.home,'target');definition(target);mkdirSync(join(e.home,'.pi/agent'),{recursive:true});symlinkSync(target,e.root);const h=harness();await h.handlers.session_start({reason:'startup'},h.ctx);assert.equal(h.entries[0].data.instructions,'PERSONAL_RULE');});
test('broken_root_symlink_does_not_fall_back',async t=>{const e=environment(t);mkdirSync(join(e.home,'.pi/agent'),{recursive:true});symlinkSync(join(e.home,'missing-target'),e.root);const h=harness();await h.handlers.session_start({reason:'startup'},h.ctx);assert.equal(h.entries[0].data.id,'standard');assert.equal(h.choices.length,1);assert.ok(h.notices.length);});
